config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "shorturls#new"
  resources :shorturls  
  get "/:short_url", to: "shorturls#load"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorturl.rb
class Shorturl < ActiveRecord::Base
    validates :raw_url, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shorturls_controller.rb
class ShorturlsController < ApplicationController
    def new
        @url = Shorturl.new
    end
    def create
        # render plain:params[:shorturl].inspect
        @url = Shorturl.new(url_params)
        @url.clean_url = @url.raw_url.strip.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
        @url.clean_url.slice!(-1) if @url.clean_url[-1] == "/"
        @url.clean_url = "http://#{@url.clean_url}"
        @url.short_url = [*('A'..'Z'),*('0'..'9'),*('a'..'z')].sample(6).join
        while Shorturl.find_by_short_url([*('A'..'Z'),*('0'..'9'),*('a'..'z')].sample(6).join)
            @url.short_url = [*('A'..'Z'),*('0'..'9'),*('a'..'z')].sample(6).join
        end
        unless Shorturl.find_by_clean_url(@url.clean_url)  
            if @url.save
                flash[:success] = "url was successfully created"
                # redirect_to @url.clean_url
                render 'show'
            else
                render 'new'
            end
        else
            @url = Shorturl.find_by_clean_url(@url.clean_url)
            render 'show'
        end
    end
    def index
        @url = Shorturl.all
    end
    def show
        @url = Shorturl.find(params[:id])
    end
    def load
        @url = Shorturl.find_by_short_url(params[:short_url])
        redirect_to @url.clean_url
    end

    private
    def url_params
        params.require(:shorturl).permit(:raw_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorturls_helper.rb
module ShorturlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shorturls/index.html.erb
<h1 align='center'>LIST OF ALL SHORTENED LINKS</h1>
<% base_url =  URI.parse(request.original_url);  base_url = request.original_url.gsub(base_url.path,"/"); %>
<div align='center'>
<table border='1'>
    <tr>
    <th>GIVEN LINK</th>
    <th>SHORTENED LINK</th>
    </tr>
    <% @url.each do |uri| %>
        <tr>
            <td> <%= uri.raw_url %> </td>
            <% link = base_url + uri.short_url %>
            <td> <%= link_to "#{link}", link %> </td>
        </tr>
    <% end %>

</table>
</div>

app/views/shorturls/new.html.erb
<h1>URL Shortener</h1>
<% if @url.errors.any? %>
 <h2>The following errors prevented the url from saving:</h2>
 <ul>
 <% @url.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<%= form_for @url do |f| %>
    <p>
     <%= f.label :raw_url,"Original URL" %>
     <div class="col-sm-6">
    <%= f.text_field :raw_url, class: "form-control", placeholder: "Enter URL", autofocus: true %>
   </div><br>
    </p>
    <p>
     <%= f.submit("Shorten") %>
    </p>
<% end %>
<p>
    <%= link_to 'View list of shortened links', shorturls_path %>
</p>

app/views/shorturls/show.html.erb
<div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
   <% uri =  URI.parse(request.original_url);  uri = request.original_url.gsub(uri.path,"/"); %>
    <h1><%= link_to "#{uri+@url.short_url}",  @url.clean_url%>
    </h1>
   </div>
   <p>
   <%= link_to "Shorten another URL", root_path %>

  </div>